model:
  embedding_dim: 64
  latent_dim: 64
  cae_h: 16
  cae_w: 16
  hidden_dim_mem: 128

data:
  shards_path: "yotoco_wds/shard-*.tar"
  batch_size: 4
  num_workers: 4
  shuffle: true
  train_years: [2015, 2016, 2017, 2018, 2019]
  mode: "train"

train:
  epochs: 100
  lr: 0.0005
  lambda_rec: 1.0
  lambda_pred: 0.8
  device: "cuda"