model:
  embedding_dim: 64
  latent_dim: 64
  cae_h: 16
  cae_w: 16
  hidden_dim_mem: 128

data:
  batch_size: 8
  num_workers: 4
  shuffle: true
  train_years: [2017, 2018, 2019, 2020, 2021]
  test_years: [2022, 2023, 2024]
  dataset_dir: "/kaggle/input/datasets/lucasiturriago/yotoco"

train:
  seed: 42
  epochs: 100
  lr: 0.0005
  lambda_rec: 1.0
  lambda_pred: 0.8
  use_amp: true
  device: "cuda"
  gamma: 0.94

experiment:
  name: "alphadeforest_experiment"
  version: 1
  output_dir: "outputs/alphadeforest/experiment_1"